kind: ServiceAccount
apiVersion: v1
metadata:
  name: nfs-mysql-provisioner
  namespace: application

#ClusterRole exists
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: run-nfs-mysql-provisioner
subjects:
  - kind: ServiceAccount
    name: nfs-mysql-provisioner
    namespace: application
roleRef:
  kind: ClusterRole
  name: nfs-client-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-nfs-mysql-provisioner
  namespace: application
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-nfs-mysql-provisioner
  namespace: application
subjects:
  - kind: ServiceAccount
    name: nfs-mysql-provisioner
    namespace: application
roleRef:
  kind: Role
  name: leader-locking-nfs-mysql-provisioner
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: run-nfs-mysql-provisioner
subjects:
  - kind: ServiceAccount
    name: nfs-mysql-provisioner
    namespace: application
roleRef:
  kind: ClusterRole
  name: nfs-client-provisioner-runner
  apiGroup: rbac.authorization.k8s.io