apiVersion: v1
kind: ServiceAccount
metadata:
  name: vaultagent-injector
  labels:
    vsi: application-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
    vsi: application-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      vsi: application-secrets
  template:
    metadata:
      annotations:
          vault.hashicorp.com/agent-inject: "true"
          vault.hashicorp.com/tls-skip-verify: "false"
          vault.hashicorp.com/agent-inject-secret-application: "secrets/application"
          vault.hashicorp.com/agent-inject-template-application: |
            {{- with secret "secrets/application" -}}
            {
              "MYSQL_ROOT_PASSWORD" : "{{ .Data.MYSQL_ROOT_PASSWORD }}",
              "MYSQL_USER" : "{{ .Data.MYSQL_USER }}"
              "MYSQL_PASSWORD" : "{{ .Data.MYSQL_PASSWORD }}"
            }
            {{- end }}
          vault.hashicorp.com/role: "agent-injector-role"
      labels:
        app: mysql
        vsi: application-secrets
    spec:
      containers:
      - name: mysql
        image: mysql:9.2
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "root"
        ports:
          - containerPort: 3306
      volumes:
        - name: mysql-nfs
          persistentVolumeClaim:
            claimName: mysql-nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql