apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-app
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: petclinic
          image: askdragon/petclinic:31
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secretkv
                  key: POSTGRES_USER
            - name: POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: secretkv
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_URL
              value: jdbc:postgresql://postres-postgresql.application.svc.cluster.local:5432/postgres
