apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-app
  namespace: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      volumes:
        - name: secrets
          secret:
            secretName: "vso-db"
      containers:
        - name: petclinic
          image: askdragon/petclinic:v1
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: secrets
              mountPath: /etc/secrets
              readOnly: true
          env:
            - name: POSTGRES_URL
              value: jdbc:postgres-postgresql.application.svc.cluster.local:5432/petclinic
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: "vso-db"
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: "vso-db"
                    key: password
            # - name: POSTGRES_DB
            #   valueFrom:
            #     secretKeyRef:
            #       name: "vso-db"
            #       key: dbname
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  namespace: application
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: petclinic
