apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  namespace: application
  labels:
    scraping: app-servicemonitor
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: petclinic
