apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: application
  name: dynamic-application
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: dynamic-auth
  namespace: application
spec:
  method: kubernetes
  mount: vso
  kubernetes:
    role: auth-role
    serviceAccount: dynamic-application
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: vso-db-create
  namespace: application
spec:
  # Mount path of the secrets backend
  mount: db
  # Path to the secret
  path: creds/petuser

  # Where to store the secrets, VSO will create the secret
  destination:
    create: true
    name: vso-db-created

  # Restart these pods when secrets rotated
  rolloutRestartTargets:
  - kind: Deployment
    name: petclinic-app

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: dynamic-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: vso-db
  namespace: application
spec:
  mount: db
  path: creds/petuser
  destination:
    create: false
    name: vso-db
  rolloutRestartTargets:
  - kind: Deployment
    name: petclinic-app
  vaultAuthRef: dynamic-auth
---
apiVersion: v1
kind: ServiceAccount
metadata:
  # SA bound to the VSO namespace for transit engine auth
  namespace: vault
  name: demo-operator #the same as in vso helm values ...storageEncryption.kubernetes.serviceAccount
---
apiVersion: v1
kind: Secret
metadata:
  name: vso-db
  namespace: application
