
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: application-cert
  namespace: application
spec:
  secretName: petclinic-tls-cert
  issuerRef:
    name: vault-issuer
    kind: Issuer
  commonName: petclinic.cluster.com
  dnsNames:
  - petclinic.cluster.com        
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
    name: vault-issuer
    namespace: application
spec:
    vault:
        caBundleSecretRef:
            name: tls-ca
            key: ca.crt
        server: https://vault-1.vault-internal.vault.svc.cluster.local:8200
        path: pki/sign/cluster-dot-com
        auth:
            kubernetes:
                mountPath: /v1/auth/kubernetes
                role: applion-role
                serviceAccountRef:
                    name: application-sa
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: application-iroute
  namespace: application
  annotations:
    cert-manager.io/issuer: "vault-issuer"
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`petclinic.cluster.com`) 
      kind: Rule
      services:
        - name: petclinic-service
          port: 8080
  tls:
    secretName: petclinic-tls-cert 