
apiVersion: v1
kind: Service
metadata:
  name: postres-postgresql-hl
  namespace: application
  labels:
    app.kubernetes.io/instance: postres
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.5.0
    app.kubernetes.io/component: primary
  annotations:
spec:
  type: ClusterIP
  clusterIP: None
  # We want all pods in the StatefulSet to have their addresses published for
  # the sake of the other Postgresql pods even before they're ready, since they
  # have to be able to talk to each other in order to become ready.
  publishNotReadyAddresses: true
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/instance: postres
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: primary
---
# Source: postgresql/templates/primary/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: postres-postgresql
  namespace: application
  labels:
    app.kubernetes.io/instance: postres
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.5.0
    app.kubernetes.io/component: primary
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
      nodePort: null
  selector:
    app.kubernetes.io/instance: postres
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: primary
