apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-servicemonitor
  namespace: application
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      scraping: app-servicemonitor
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 60s