kind: ServiceAccount
apiVersion: v1
metadata:
  name: nfs-sonar-provisioner
  namespace: sonar

#ClusterRoleBinding run-nfs-client-provisioner exists
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-nfs-sonar-provisioner
  namespace: sonar
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-nfs-sonar-provisioner
  namespace: sonar
subjects:
  - kind: ServiceAccount
    name: nfs-sonar-provisioner
    namespace: sonar
roleRef:
  kind: Role
  name: leader-locking-nfs-sonar-provisioner
  apiGroup: rbac.authorization.k8s.io