kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-nfs-pvc
  namespace: sonar
  labels:
    app: postgres
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
