apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-nfs-pvc
  namespace: sonar
spec:
  storageClassName: managed-nfs-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-extensions-nfs-pvc
  namespace: sonar
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: managed-nfs-storage
  resources:
    requests:
      storage: 500Mi
