apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sonarqube
  name: sonarqube
  namespace: sonar
spec:
  selector:
    matchLabels:
      app: sonarqube
  replicas: 1
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              chown -R 1001:1001 /opt/bitnami/sonarqube/data \
                         /opt/bitnami/sonarqube/extensions \
                         /opt/bitnami/sonarqube/logs
              chmod -R u+rwX /opt/bitnami/sonarqube/data \
                              /opt/bitnami/sonarqube/extensions \
                              /opt/bitnami/sonarqube/logs
              # rm -r opt/bitnami/sonarqube/data/es8
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /opt/bitnami/sonarqube/data
              name: sonar-data
            - mountPath: /opt/bitnami/sonarqube/extensions
              name: sonar-extensions
            - mountPath: /opt/bitnami/sonarqube/logs
              name: sonar-logs
      containers:
        - name: sonarqube
          image: bitnami/sonarqube:10.7.0
          resources:
            requests:
              cpu: 500m
              memory: 1024Mi
            limits:
              cpu: 2000m
              memory: 2048Mi
          securityContext: #uid=1001(sonarqube) gid=1001(sonarqube) groups=1001(sonarqube),0(root)
            runAsGroup: 1001
            runAsUser: 1001
          volumeMounts:
          - mountPath: "/opt/bitnami/sonarqube/data"
            name: sonar-data
          - mountPath: "/opt/bitnami/sonarqube/extensions"
            name: sonar-extensions
          - mountPath: /opt/bitnami/sonarqube/logs
            name: sonar-logs
          env:
          - name: SONAR_JDBC_URL
            value: jdbc:postgresql://postgres.sonar.svc.cluster.local:5432/postgres
          - name: SONARQUBE_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: "sonar-user"
          - name: SONARQUBE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: static-sonar-secret
                key: "sonar-password"
          - name: SONARQUBE_DATABASE_HOST
            value: "postgres.sonar.svc.cluster.local"
          - name: SONARQUBE_DATABASE_PORT_NUMBER
            value: "5432"
          - name: SONARQUBE_DATABASE_NAME
            value: "postgres"
          - name: "SONARQUBE_DATABASE_USER"
            valueFrom:
               secretKeyRef:
                 name: static-sonar-secret
                 key: "JDBC_USERNAME"
          # - name: "SONARQUBE_JDBC_URL"
          #   valueFrom:
          #     configMapKeyRef:
          #       name: sonar-config
          #       key: url
          - name: "SONARQUBE_DATABASE_PASSWORD"
            valueFrom:
               secretKeyRef:
                 name: static-sonar-secret
                 key: "JDBC_PASSWORD"
          ports:
          - containerPort: 9000
            protocol: TCP
      volumes:
      - name: sonar-data
        persistentVolumeClaim:
          claimName: sonar-nfs-pvc
      - name: sonar-extensions
        persistentVolumeClaim:
          claimName: sonar-extensions-nfs-pvc
      - name: sonar-logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sonarqube
  name: sonar-service
  namespace: sonar
spec:
  ports:
    - name: sonar
      port: 80
      protocol: TCP
      targetPort: 9000
  selector:
    app: sonarqube
  type: ClusterIP