apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-petclinic-app
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-petclinic
  template:
    metadata:
      labels:
        app: demo-petclinic
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: demo-petclinic
          image: askdragon/demopetclinic:8
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 6300
              name: jacoco
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secretkv
                  key: POSTGRES_USER
            - name: POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: secretkv
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_URL
              value: jdbc:postgresql://postres-postgresql.application.svc.cluster.local:5432/postgres
---
apiVersion: v1
kind: Service
metadata:
  name: demo-petclinic-service
  namespace: application
spec:
  selector:
    app: demo-petclinic
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: jacoco
      port: 6300
      targetPort: jacoco