kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-nfs-pvc
  namespace: monitoring
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
