kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-nfs-pvc
  namespace: monitoring
  labels:
    app: prometheus
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
