apiVersion: v1
kind: ServiceAccount
metadata:
  # SA bound to the VSO namespace for transit engine auth
  namespace: vault
  name: demo-operator #the same as in vso helm values ...storageEncryption.kubernetes.serviceAccount
---
apiVersion: v1
kind: Secret
metadata:
  name: vso-db
  namespace: application
