---
# Source: postgresql/templates/primary/networkpolicy.yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: postres-postgresql
  namespace: application
  labels:
    app.kubernetes.io/instance: postres
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.5.0
    app.kubernetes.io/component: primary
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: postres
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/component: primary
  policyTypes:
    - Ingress
    - Egress
  egress:
    - {}
  ingress:
    - ports:
        - port: 5432
---
# Source: postgresql/templates/primary/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postres-postgresql
  namespace: application
  labels:
    app.kubernetes.io/instance: postres
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.5.0
    
    app.kubernetes.io/component: primary
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: postres
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/component: primary
---
# Source: postgresql/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postres-postgresql
  namespace: application
  labels:
    app.kubernetes.io/instance: postres
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.5.0
automountServiceAccountToken: false