apiVersion: v1
kind: ServiceAccount
metadata:
    name: jenkins-sa
    namespace: jenkins
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: sonar-sa
    namespace: sonar
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: argo-sa
    namespace: argo
