apiVersion: v1
kind: ServiceAccount
metadata:
    name: issuer
    namespace: jenkins
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: issuer
    namespace: sonar
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: issuer
    namespace: argo
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
    name: vault-issuer
    namespace: jenkins
spec:
    vault:
       server: https://vault.vault.svc.cluster.local:8200
       path: pki/sign/cluster-dot-com
       auth:
          kubernetes:
              mountPath: /v1/auth/kubernetes
              role: jenkins-role
              serviceAccountRef:
                name: jenkins-sa