apiVersion: v1
kind: ServiceAccount
metadata:
    name: jenkins-sa
    namespace: jenkins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-issuer
  namespace: jenkins
rules:
  - apiGroups: ['']
    resources: ['serviceaccounts/token']
    verbs: ['create']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-issuer
  namespace: jenkins
subjects:
  - kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
    name: vault-issuer
    namespace: jenkins
spec:
    vault:
        caBundleSecretRef:
            name: tls-ca
            key: ca.crt
        server: https://vault-1.vault-internal.vault.svc.cluster.local:8200
        path: pki/sign/cluster-dot-com
        auth:
            kubernetes:
                mountPath: /v1/auth/kubernetes
                role: jenkins-role
                serviceAccountRef:
                    name: jenkins-sa